apiVersion: v1
kind: Service
metadata:
  name: spark
spec:
  type: ClusterIP
  ports:
  - port: 8080
  clusterIP: None
  selector:
    app: spark
---
apiVersion: v1
kind: Pod
metadata:
  name: spark
  labels:
    app: spark
spec:
  hostname: spark
  restartPolicy: Never
  containers:
  - name: spark
    image: carvicsforth/spark:3.3.1
    args:
    - bash
    - "-c"
    - |
        /opt/spark/bin/spark-submit \
        --master k8s://https://10.96.0.1:443 \
        --deploy-mode client \
        --name spark-pi \
        --class org.apache.spark.examples.SparkPi \
        --conf spark.executor.instances=2 \
        --conf spark.kubernetes.container.image=carvicsforth/spark:3.3.1 \
        --conf spark.kubernetes.namespace=default \
        --conf spark.kubernetes.authenticate.driver.serviceAccountName=default \
        --conf spark.kubernetes.driver.service.deleteOnTermination=true \
        --conf spark.jars.ivy=/tmp/.ivy \
        local:///opt/spark/examples/jars/spark-examples_2.12-3.3.1.jar
