apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv-minio
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/malvag/kubeflow_testbed/minio_data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-share-pvc-minio
  namespace: minio
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi