---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - name: http
      port: 5201

---
apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  restartPolicy: Never
  containers:
    - name: main
      image: networkstatic/iperf3
      ports:
        - name: http
          containerPort: 5201
          protocol: TCP
      command:
        - sh
        - -c
        - |
          iperf3 -s -p 5201

---
apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  restartPolicy: Never
  containers:
    - name: main
      image: networkstatic/iperf3
      command:
        - sh
        - -c
        - |
          # Delay waiting for server to become ready
          sleep 20 
          iperf3 -c server-service -p 5201