apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - |
          env
          sleep infinity
---
