apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6-alpine
      ports:
        - containerPort: 80
          name: http
          protocol: TCP