replicaCount: 1

image:
  repository: malvag/knoc
  pullPolicy: IfNotPresent
  tag: ""


knoc: {
  enabledMetrics: false,
  k8sApiServer: "",
  logLevel: debug,
  remoteSecret: {
    address: "",
    port: "22",
    user: "",
    privkey: "",
    kubeContext: ""
  }
}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

singleNamespace: false

serviceAccount:
  create: true
  annotations: {}
  name: "knoc"

# podAnnotations: {}

# podSecurityContext: {}
#   # fsGroup: 2000


# nodeSelector: {}

# tolerations: []

# affinity: {}
