---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-adduser
spec:
  containers:
    - name: whoami-adduser
      image: alpine
      command:
        - sh
        - -c
        - |
          addgroup -S newuser
          adduser -S newuser -G newuser
          
          apk add util-linux

          # Expect root
          echo "[prev] $(whoami)"

          # Expect newuser
          echo "[after"] $(runuser -u newuser -- whoami)

---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-newuser
spec:
  containers:
    - name: whoami-newuser
      image: icsforth/alpine:newuser
      command:
        - runuser
        - newuser
        - -c
        - |
          whoami
---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-root
spec:
  containers:
    - name: whoami-root
      image: alpine
      command: [ "whoami" ]
