---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-adduser
spec:
  containers:
    - name: whoami-adduser
      image: ubuntu
      command:
        - sh
        - -c
        - |
          useradd --shell /bin/bash --create-home  newuser
          
          # Expect root
          echo "[prev] $(whoami)"
          
          # Expect newuser
          echo "[after"] $(runuser -u newuser -- whoami)

---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-newuser
spec:
  containers:
    - name: whoami-newuser
      image: icsforth/ubuntu:newuser
      command:
        - runuser
        - newuser
        - -c
        - |
          whoami

---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-root
spec:
  containers:
    - name: whoami-root
      image: ubuntu
      command: ["whoami"]
