apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60

  sshAuthMountPath: /home/mpiuser/.ssh

  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: mpioperator/mpi-pi
              name: mpi-launcher
              command:
                - runuser
                - mpiuser
                - -l
                - -c
                - |
                  mpirun -n 2 /home/mpiuser/pi

    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - image: mpioperator/mpi-pi
              name: mpi-worker
              command:
                - sh
                - -c
                - |
                  chmod -R 700 /home/mpiuser/.ssh
                  chmod 600 /home/mpiuser/.ssh/id_rsa

                  /usr/sbin/sshd -De -f /home/mpiuser/.sshd_config
