apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60

  sshAuthMountPath: /home/mpiuser/.ssh

  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: mpioperator/mpi-pi
              name: mpi-launcher
              command: [runuser, -u, mpiuser, -- ]
              args:
                - sh
                - -c
                - |
                  unset LD_LIBRARY_PATH
                  unset LD_PRELOAD

                  env 

                  mpirun --allow-run-as-root -n "2" /home/mpiuser/pi

    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - image: mpioperator/mpi-pi
              name: mpi-worker
              command:
                - runuser
                - --preserve-environment
                - root
                - -c
                - |
                  whoami 
                  env

                  chmod -R 700 /home/mpiuser/.ssh
                  chmod 600 /home/mpiuser/.ssh/id_rsa

                  echo skata | passwd mpiuser

                  echo PubkeyAuthentication yes >> /home/mpiuser/.sshd_config
                  echo PasswordAuthentication no >> /home/mpiuser/.sshd_config

                  echo "SSH Daemon Config "
                  echo " ------- "
                  cat /home/mpiuser/.sshd_config
                  echo " ------- "

                  /usr/sbin/sshd -De -f /home/mpiuser/.sshd_config
