---
apiVersion: v1
kind: Pod
metadata:
  name: iperf.localhost
spec:
  restartPolicy: Never
  containers:
     - name: server
       image: networkstatic/iperf3
       command:
        - sh
        - -c
        - |
          iperf3 -s

     - name: client
       image: networkstatic/iperf3
       command:
         - sh
         - -c
         - |
           sleep 10
           iperf3 -c localhost