---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: iperf
spec:
  selector:
    app: server
  ports:
    - name: http
      port: 5201

---
apiVersion: v1
kind: Pod
metadata:
  namespace: iperf
  name: server
  labels:
      app: server
spec:
  restartPolicy: Never
  containers:
     - name: main
       image: networkstatic/iperf3
       ports:
         - name: http
           containerPort: 5201
           protocol: TCP
       command:
        - sh
        - -c
        - |
          iperf3 -s

  # Schedule execution on virtual-kubelet
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists

---
apiVersion: v1
kind: Pod
metadata:
  namespace: iperf
  name: client
spec:
  restartPolicy: Never
  containers:
    - name: main
      image: networkstatic/iperf3
      command:
        - sh
        - -c
        - |
          # Delay waiting for server to become ready
          sleep 10 
          iperf3 -c server-service

  # Schedule execution on virtual-kubelet
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists