Region: eu-central-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-0d2e4616b4204dc3d
  Ssh:
    KeyName: forthCluster-keypair
  CustomActions:
    OnNodeConfigured:
      Script: s3://hpk-parallelcluster/install-hpk-requirements.sh
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2medium
      Instances:
      - InstanceType: t2.medium
      MinCount: 2
      MaxCount: 2
    Networking:
      SubnetIds:
      - subnet-0084d54d1250752e8
    CustomActions:
      OnNodeConfigured:
        Script: s3://hpk-parallelcluster/install-hpk-requirements.sh
