Region: eu-central-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-0d0899f8ee5f07fe5
  Ssh:
    KeyName: forthCluster-keypair
  CustomActions:
    OnNodeConfigured:
      Script: s3://hpk-parallelcluster/install-hpk-requirements.sh
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2medium
      Instances:
      - InstanceType: t2.medium
      MinCount: 2
      MaxCount: 2
    Networking:
      SubnetIds:
      - subnet-055ecda57fa839264
    CustomActions:
      OnNodeConfigured:
        Script: s3://hpk-parallelcluster/install-hpk-requirements.sh
