apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello
  templates:
    - name: hello
      steps: # The type of this "template" is "steps"
        - - name: hello
            template: whalesay    # We reference our second "template" here
            arguments:
              parameters: [ { name: message, value: "hello1" } ]
    - name: whalesay             # The second "template" in this Workflow, it is referenced by "hello"
      inputs:
        parameters:
          - name: message
      container: # The type of this "template" is "container"
        image: alpine:3.7
        command: [ echo, "{{inputs.parameters.message}}" ]

  # Schedule execution on virtual-kubelet
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists