apiVersion: v1
kind: Pod
metadata:
  name: busyecho3
spec:
  containers:
  - image: argoproj/argosay:v2
    command: 
      - "sleep"
    args:
      - "30"
    imagePullPolicy: Always
    name: busyecho
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: game-config
  restartPolicy: Never
  dnsPolicy: ClusterFirst
  # nodeSelector:
  #   kubernetes.io/role: agent
  #   beta.kubernetes.io/os: linux
  #   type: virtual-kubelet
  # tolerations:
  # - key: virtual-kubelet.io/provider
  #   operator: Exists
  # - key: azure.com/aci
  #   effect: NoSchedule

# KUBERNETES_PORT_443_TCP_PORT=443
# KUBERNETES_PORT=tcp://10.96.0.1:443
# KUBERNETES_SERVICE_PORT=443
# KUBERNETES_SERVICE_HOST=10.96.0.1
# KUBERNETES_PORT_443_TCP_PROTO=tcp
# KUBERNETES_SERVICE_PORT_HTTPS=443
# KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
# KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
