---
apiVersion: v1
kind: Pod
metadata:
  labels:
      app: server
  name: server
spec:
  restartPolicy: Never
  containers:
     - name: main
       image: networkstatic/iperf3
       ports:
         - containerPort: 5201
           name: http
           protocol: TCP
         - containerPort: 443
           name: https
       command:
        - sh
        - -c
        - |
          iperf3 -s

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      targetPort: 5201
      port: 5201
  clusterIP: "None"


---
apiVersion: v1
kind: Pod
metadata:
  generateName: client-
spec:
  restartPolicy: Never
  containers:
    - name: main
      securityContext:
        privileged: true
      image: praqma/network-multitool
      command:
        - sh
        - -c
        - |
          sleep infinity
    - name: main2
      image: networkstatic/iperf3
      command:
        - sh
        - -c
        - |
          sleep infinity
