---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: "pod-mutator.hpk.dev"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      url: "https://${VKUBELET_ADDRESS}:10250/mutates/pods"
      caBundle: ${CA_BUNDLE}
    failurePolicy: Fail
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 5
    sideEffects: None