apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-vkubelet
spec:
  containers:
  - name: vk-{{ .Release.Name }}
    image: {{.Values.image.repository }}
    imagePullPolicy: {{.Values.image.pullPolicy}}
    args:
    - virtual-kubelet
    - --nodename
    - vk-knoc
    - --provider
    - knoc
    - --provider-config
    - /home/user0/knoc-cfg.json
    - --startup-timeout
    - 10s
    - --klog.v
    - "2"
    - --klog.logtostderr
    - --log-level
    - {{ .Values.knoc.logLevel }}
    volumeMounts:
      - name: kubeconfig-setup
        mountPath: /home/user0/scripts/
    env:
    - name: KUBELET_PORT
      value: "10250"
    - name: VKUBELET_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: REMOTE_USER
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-remote-secret
          key: remote_user
    - name: REMOTE_KEY
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-remote-secret
          key: ssh-privatekey
    - name: REMOTE_HOST
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-remote-secret
          key: host
    - name: REMOTE_PORT
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-remote-secret
          key: port
    - name: KUBE_CURRENT_CONTEXT
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-remote-secret
          key: kube_context
    {{- if .Values.knoc.enabledMetrics }}
    ports:
    - name: metrics
      containerPort: {{- if .Values.metrics_port }} {{ .Values.metrics_port }} {{- else }} 10255 {{- end }}
    readinessProbe:
      httpGet:
        path: /stats/summary
        port: metrics
    {{- end }}
  serviceAccountName: knoc
  volumes:
    - name: kubeconfig-setup
      configMap:
        name: setup-kubeconfig
        defaultMode: 0777
