apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-remote-secret
  namespace:  {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: "Opaque"
immutable: true
data:
  host: {{ .Values.knoc.remoteSecret.address | b64enc }}
  port: {{ .Values.knoc.remoteSecret.port | b64enc }}
  remote_user: {{ .Values.knoc.remoteSecret.user | b64enc }}
  ssh-privatekey: {{ .Values.knoc.remoteSecret.privkey | b64enc }}
  kube_context: {{ .Values.knoc.remoteSecret.kubeContext | b64enc }}