{
 "title": "OpenGadget3: Bins",
 "tags": [
  "frisbee",
  "console"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Bin", "query": { "query": "label_values(bin)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dloga Over Redshift",
   "type": "barchart",
   "description": "\n",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gadget_dloga) by (redshift)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Utilization (CPU/IO/Net)",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval])) != 0 ",
     "legendFormat": "cpu"
    },
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{id=\"/\"}[$__rate_interval]) +  \nrate(container_fs_writes_bytes_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "io"
    },
    {
     "expr": "avg(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]) +  \nrate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "net"
    }
   ]
  },
  {
   "title": "Universe to Clock Time",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "max(gadget_time)", "legendFormat": "Universe Time" }
   ]
  },
  {
   "title": "__Bin Section__",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DT Per Bin",
   "type": "state-timeline",
   "description": "\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gadget_dt{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cummulative (Cells + Non-Cells)",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gadget_cummulative{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cummulative (Cells + NonCells)",
   "type": "bargauge",
   "description": "\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gadget_cummulative{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cells",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gadget_cells{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cells",
   "type": "bargauge",
   "description": "\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gadget_cells{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Cells",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gadget_noncells{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Cells",
   "type": "bargauge",
   "description": "\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gadget_noncells{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time in Bin (heat map)",
   "type": "heatmap",
   "description": "this reports the field \"avg time\" from the log, i.e. the average time needed to elaborate particles in different bins\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "max(gadget_avgtime{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Average Time (in the last rep. period)",
   "type": "bargauge",
   "description": "\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gadget_avgtime{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time in Bin (time series)",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "max(gadget_avgtime{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Fraction spent in bin (time series)",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "max(gadget_cpufrac{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Fraction (in all the sim)",
   "type": "piechart",
   "description": "\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gadget_cpufrac{bin=~\"$Bin\"}) by (bin)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}